mkdir build
cd build
cmake .. -G "$CMAKE_GENERATOR" -DCMAKE_PREFIX_PATH="$PREFIX" -DCMAKE_INSTALL_PREFIX="$PREFIX" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=gfortran -DENABLE_NETCDF=ON -DENABLE_PYTHON=ON -DENABLE_FORTRAN=ON

make
make install
